### ISSUE TITLE
Issue with ble_stack_init();

### ISSUE THREAD

**Issue by BEN-ZZ** [NordicPlayground/nRF52-Bluetooth-Course#4]
Hi, there,

Anyone has problem with ble_stack_init() after changing "#define NRF_SDH_BLE_VS_UUID_COUNT 1". Looks like after changing the number of vendor specific UUID and increasing the RAM size etc., ble stack can not be initialized. 

The other SDK examples run good, advertising -> connecting etc., but it looks like they, such as bps, don't use UUID. I am wondering whether this course is outdated. I am trying to get familiar with Nordic's softdevice and SDK.

Regards

Ben

**Comment by wisalmuhammad** [comment]
Same issue on my side.? did you find a solution?

**Comment by BEN-ZZ** [comment]
It is all working for me now. Did you already change the RAM start and RAM size in the section placement macro? If not, changing it according should make it work.

Let me know if you still have problem.  I am quite familiar with the too chain now after spending 2 months working on it.

Regards


Ben

**Comment by wisalmuhammad** [comment]
Hi
thank you for your reply and time.
can you help me here where should I change it further I mean via the macro. I am a little bit new to this world so it would be very helpful. Also, the RAM size range that mentions in the course for this work is still the same.?
